### ISSUE TITLE
`UnificationFailure` not found for unification-fd 0.10

### ISSUE THREAD

**Issue by Warbo** [danr/hipspec#21]
hipspec.cabal specifies unification-fd >= 0.8 but the API has changed in 0.10. The `UnificationFailure` type (used by `src/HipSpec/Unify.hs`) has been renamed to `UFailure`. Also, it is no longer exported by `Control.Unification`; it requires importing `Control.Unification.Types` directly.

The easiest fix would be to add a < 0.10 requirement; slightly messier would be to update to >= 0.10; really messy would be using CPP, etc. to allow either.

**Comment by danr** [comment]
Oh, wrong ticket!

Anyway, I uploaded a version of the `hipster` branch that hopefully compiles with 7.10.1 now.
