### ISSUE TITLE
Resolver too old for stack

### ISSUE THREAD

**Issue by yanhasu** [danr/hipspec#24]
Trying to build the project with a modern version of stack (e.g. 2.5.1.1) fails due to the `lts-2.22` resolver (from `stack.yaml`) being unsupported.

The exact error is:
```
Stack no longer supports Cabal versions older than 1.19.2, but version 1.18.1.5 was found.  To fix this, consider updating the resolver to lts-3.0 or later / nightly-2015-05-05 or later.

```

**Comment by yanhasu** [comment]
Ideally the project would work 'out of the box' with recent versions of stack.

For the moment, one work-around is to manually [install an old version of stack](https://gist.github.com/yanhasu/6a90aa99d9bfef4c9cf060bd4e6f2bb3).

**Comment by danr** [comment]
Hi, this repo is not maintained and I'm not involved in this line of research anymore. I think the development has continued at https://github.com/tip-org/tools
