### ISSUE TITLE
Can't run hipspec on examples with dependencies

### ISSUE THREAD

**Issue by yanhasu** [danr/hipspec#25]
I can run hipspec on examples without dependencies (i.e. importing only `HipSpec` and `Prelude`) as following:

```
./stack run hipspec -- examples/Properties.hs
```

and it then succesfully proves some properties in the file.

However, I can't figure out how to run more complicated examples (e.g those containing `import Nat`).

e.g. none of the following work
```
$ ./stack run hipspec -- examples/List.hs 
hipspec: Could not find module ‘Nat’
Use -v to see a list of the files searched for.

$ ./stack run hipspec -- examples/List.hs examples/Nat.hs 
Unhandled argument, expected at most 1: examples/Nat.hs
```

And hipspec doesn't seem to have a `ghci` interface (like quickCheck) either.

I can get around this issue by manually merging the files together, but this seems like more effort than it should be.

**Comment by yanhasu** [comment]
If instead of using `./stack run` we use `./stack install`, the situation is even worse:

```
$ ./stack install hipspec
$ hipspec examples/Properties.hs 
hipspec: Could not find module ‘HipSpec’
Use -v to see a list of the files searched for.
```

i.e. the compiled version of hipspec can't find the `HipSpec` module.

This makes `run_tests.sh` fail on my machine.

**Comment by danr** [comment]
Hi, this repo is not maintained and I'm not involved in this line of research anymore. I think the development has continued at https://github.com/tip-org/tools
